server {
    listen 80;

    # Archivos estaticos: vmlinuz, initrd, scripts iPXE
    location / {
        root /var/www/html;
        autoindex on;
    }

    # Proxy al servidor Flask para cloud-init por MAC
    location ~ ^/ds/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rutas legacy por si las usas directamente
    location /user-data {
        proxy_pass http://127.0.0.1:8080/user-data;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /meta-data {
        proxy_pass http://127.0.0.1:8080/meta-data;
        proxy_set_header Host $host;
    }

    location ^~ /debug/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /boot/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /ks/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
}
